; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

build_flags =
    -I include ; the folder containing lvgl.h
    -I lib
    ; -I .pio/libdeps/esp32dev/lvgl/examples
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D LV_USE_TFT_ESPI=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=16
    -D TFT_DC=27
    -D TFT_RST=12
    ; -D LV_CONF_SKIP
    -D LV_COLOR_DEPTH=16
    -D LV_USE_LOG=1
    -D LV_USE_ANIM=1

    ; -D LV_FONT_MONTSERRAT_24=1
    ; -D LV_FONT_MONTSERRAT_16=1
    ; -D LV_FONT_MONTSERRAT_32=1
    ; -D lv_font_montserrat_12=1
    ; -D lv_font_montserrat_48=1
    ; -D lv_font_montserrat_20=1
lib_deps = 
    lvgl/lvgl@^9.5.0
    bodmer/TFT_eSPI@^2.5.43
    makuna/RTC @ ^2.4.2        ; DS1302 support (ThreeWire + RtcDS1302)


lib_ignore = 
            lvgl/examples
            I lib/Callender



build_src_filter =
    ; +<*> ; include all source files in the src folder
    ; +<../.pio/libdeps/esp32dev/lvgl/examples/>

